# These are supported funding model platforms

github: # https://github.com/marquiseclove-gmail-comReplace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
pa with a single Patreon username
open_collth a single Open Collective username
ko_h a single Ko-fi username
tidel with a single Tidelift platform-name/package-name e.g., npm/babel
communieplace with a single Community Bridge project-name e.g., cloud-foundry
lReplace with a single Liberapay username
issunt: # Replace with a single IssueHunt username
lfx_ng: # Replace with a sh up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
